import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });
const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Halal DevCo.",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const messages = await getMessages();
  return (
    <NextIntlClientProvider messages={messages}>
      <html lang="en">
        <body
          className={`${cn(
            "min-h-screen bg-background  antialiased"
          )} ${
            urbanist.className
          } text-neutral-800 pt-10 px-8 lg:px-12 space-y-14`}
        >
          <ReactQueryProvider>
              <Navbar />
              {children}
              <Footer />
          </ReactQueryProvider>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
